#!/usr/bin/env bash
set -euo pipefail

EMBED_MODEL="${EMBED_MODEL:-Qwen/Qwen3-Embedding-0.6B}"
INDEX_KB="${INDEX_KB:-all}"
FORCE_RESTART="${FORCE_RESTART:-0}"
AUTO_RECREATE_COLLECTION="${AUTO_RECREATE_COLLECTION:-0}"
EMBED_BATCH_SIZE="${EMBED_BATCH_SIZE:-4}"

echo "Building Milvus RAG index..."
echo "EMBED_MODEL=${EMBED_MODEL}"
echo "INDEX_KB=${INDEX_KB}"
echo "FORCE_RESTART=${FORCE_RESTART}"
echo "AUTO_RECREATE_COLLECTION=${AUTO_RECREATE_COLLECTION}"
echo "EMBED_BATCH_SIZE=${EMBED_BATCH_SIZE}"

EMBED_MODEL="${EMBED_MODEL}" \
INDEX_KB="${INDEX_KB}" \
FORCE_RESTART="${FORCE_RESTART}" \
AUTO_RECREATE_COLLECTION="${AUTO_RECREATE_COLLECTION}" \
EMBED_BATCH_SIZE="${EMBED_BATCH_SIZE}" \
python scripts/rag/index_milvus.py
